// GENERATED by scripts/gen_types.py — DO NOT EDIT.
// Regenerate with `make types`; tests/test_ts_types.py fails on drift.
// Decimals are STRINGS on the wire; datetimes are ISO strings.

export type Market = {
  id: string
  venue: "kalshi" | "polymarket"
  event_key: string | null
  question: string
  status: "open" | "closed" | "settled" | "unknown"
  yes_price: string
  no_price: string
  best_bid: string | null
  best_ask: string | null
  volume_24h: string
  liquidity: string | null
  close_ts: string
  resolution_url: string
  icon_url: string | null
  fetched_at: string
}

export type OrderbookLevel = {
  price: string
  size: string
}

export type Orderbook = {
  market_id: string
  venue: "kalshi" | "polymarket"
  bids: OrderbookLevel[]
  asks: OrderbookLevel[]
  fetched_at: string
}

export type Position = {
  market_id: string
  side: "yes" | "no"
  contracts: string
  entry_price: string
  est_prob: string | null
  notes: string
}

export type VenueTop = {
  bid: string | null
  bid_size: string | null
  ask: string | null
  ask_size: string | null
}

export type DivergenceItem = {
  event_key: string
  question: string
  criteria_verified: boolean
  notes: string
  kalshi: VenueTop
  polymarket: VenueTop
  raw_basis_cents: string | null
  direction: "buy_yes_kalshi_no_polymarket" | "buy_yes_polymarket_no_kalshi" | null
  fee_adjusted_edge: string | null
  max_lock_size: string | null
  edge_at_size: string | null
  fee_assumed_worst_case: boolean
  fetched_at: string
}

export type EventExposure = {
  event_id: string
  prob_yes: string
  delta_if_yes: string
  delta_if_no: string
  net_yes_contracts: string
}

export type PositionRisk = {
  position: Position
  event_id: string | null
  question: string | null
  mark: string | null
  market_value: string | null
  cost_basis: string
  unrealized_pnl: string | null
  max_loss: string | null
  kelly_full: string | null
  kelly_half: string | null
}

export type RiskReport = {
  positions: PositionRisk[]
  by_event: EventExposure[]
  total_market_value: string
  total_cost_basis: string
  total_unrealized_pnl: string
  max_loss: string
  var_95_parametric: string
  var_95_monte_carlo: string
  mc_draws: number
  mc_seed: number
  unmarked_positions: number
  assumptions: string[]
  fetched_at: string
}

export type PairQuote = {
  event_key: string
  question: string
  criteria_verified: boolean
  notes: string
  kalshi: Market | null
  polymarket: Market | null
}

export type HistoryPoint = {
  ts: string
  k_mid: string | null
  p_mid: string | null
  raw_basis_cents: string | null
  fee_adjusted_edge: string | null
  edge_at_size: string | null
}

export type HistoryResponse = {
  event_key: string
  hours: number
  points: HistoryPoint[]
}

export type PositionsUpdate = {
  positions: Position[]
}
