"""Generate apps/terminal/src/types.gen.ts from the pydantic models.

The API's JSON shapes have ONE source of truth — the pydantic models. The
UI's types are derived from them (docs/ENGINEERING.md layout: 'pydantic models +
generated TS types'), never hand-mirrored: a backend field rename must break
`make test` (via tests/test_ts_types.py drift check + tsc), not silently
render '—' in the terminal.

Serialization-mode JSON schema is used deliberately: Decimals serialize as
STRINGS on the wire and must type as strings in the UI; datetimes as ISO
strings. Run `make types` after changing any model below.
"""

import json
from pathlib import Path

from tinli_divergence import DivergenceItem
from tinli_schema import Market, Orderbook, Position
from tinli_risk import RiskReport

from tinli_api.routes import (
    StreamUpdate,
    VenueStreamStatus,
    HistoryPoint,
    HistoryResponse,
    LockReport,
    PairQuote,
    PositionsUpdate,
)

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "apps" / "terminal" / "src" / "types.gen.ts"

# Top-level models; nested models (VenueTop, PositionRisk, OrderbookLevel,
# EventExposure, ...) arrive automatically via each schema's $defs.
MODELS = [Market, Orderbook, Position, DivergenceItem, RiskReport, PairQuote,
          HistoryPoint, HistoryResponse, PositionsUpdate, LockReport,
          VenueStreamStatus, StreamUpdate]

HEADER = """\
// GENERATED by scripts/gen_types.py — DO NOT EDIT.
// Regenerate with `make types`; tests/test_ts_types.py fails on drift.
// Decimals are STRINGS on the wire; datetimes are ISO strings.
"""


def ts_type(s: dict) -> str:
    if "$ref" in s:
        return s["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in s:
        parts = []
        for sub in s["anyOf"]:
            t = ts_type(sub)
            if t not in parts:
                parts.append(t)
        return " | ".join(parts)
    if "const" in s:
        return json.dumps(s["const"])
    if "enum" in s:
        return " | ".join(json.dumps(v) for v in s["enum"])
    t = s.get("type")
    if t == "string":
        return "string"
    if t in ("number", "integer"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        inner = ts_type(s.get("items", {}))
        return f"({inner})[]" if " | " in inner else f"{inner}[]"
    if t == "object" and isinstance(s.get("additionalProperties"), dict):
        return f"Record<string, {ts_type(s['additionalProperties'])}>"
    raise ValueError(f"unhandled schema fragment: {s!r}")


def emit_object(name: str, schema: dict) -> str:
    lines = [f"export type {name} = {{"]
    for field, sub in schema.get("properties", {}).items():
        lines.append(f"  {field}: {ts_type(sub)}")
    lines.append("}")
    return "\n".join(lines)


def render() -> str:
    defs: dict[str, dict] = {}
    order: list[str] = []
    for model in MODELS:
        schema = model.model_json_schema(mode="serialization")
        for ref_name, ref_schema in schema.pop("$defs", {}).items():
            if ref_name in defs:
                if defs[ref_name] != ref_schema:
                    raise ValueError(f"conflicting $defs for {ref_name}")
                continue
            defs[ref_name] = ref_schema
            order.append(ref_name)
        name = schema.get("title", model.__name__)
        if name not in defs:
            defs[name] = schema
            order.append(name)
    blocks = [emit_object(name, defs[name]) for name in order]
    return HEADER + "\n" + "\n\n".join(blocks) + "\n"


def main() -> None:
    OUT.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
