"""Generate docs/research/lead-lag.md: cross-venue price discovery.

    python scripts/leadlag_note.py

Method in tinli_backtest.leadlag (move-conditional follow analysis with an
exact binomial test); every input is the decimal128 parquet history.
"""

from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path

import pyarrow.parquet as pq

from tinli_backtest import LeadLag, build_series, lead_follow

REPO = Path(__file__).resolve().parents[1]
HISTORY = REPO / "data" / "history"
OUT = REPO / "docs" / "research" / "lead-lag.md"

THRESHOLD = Decimal("0.0025")  # 0.25 cents of mid move
SENSITIVITY = [Decimal("0.001"), Decimal("0.005")]
HORIZON = 10  # ticks
MIN_MOVES = 10  # per-pair table row cutoff (pooled stats use everything)


def load_rows() -> list[dict]:
    rows: list[dict] = []
    for f in sorted(HISTORY.rglob("*.parquet")):
        rows.extend(pq.read_table(f).to_pylist())
    return rows


def fmt(r: LeadLag) -> str:
    n = r.follows + r.opposes
    rate = f"{r.follows / n:.0%}" if n else "—"
    lag = f"{r.median_lag_s:.0f}s" if r.median_lag_s is not None else "—"
    p = f"{r.p_value:.3f}" if r.p_value is not None else "—"
    return (f"{r.n_moves} | {r.simultaneous} | {r.follows}/{r.opposes}/"
            f"{r.unanswered} | {rate} | {lag} | {p}")


def main() -> None:
    rows = load_rows()
    pairs = sorted({r["event_key"] for r in rows})

    per_pair: dict[str, tuple[LeadLag, LeadLag]] = {}
    pooled_k, pooled_p = LeadLag(), LeadLag()
    for key in pairs:
        s = build_series(rows, key)
        if len(s.ts) < 50:
            continue
        k = lead_follow(s, "kalshi", THRESHOLD, HORIZON)
        p = lead_follow(s, "polymarket", THRESHOLD, HORIZON)
        pooled_k.absorb(k)
        pooled_p.absorb(p)
        if k.n_moves + p.n_moves >= MIN_MOVES:
            per_pair[key] = (k, p)

    lines: list[str] = []
    w = lines.append
    w("# Which venue moves first? Cross-venue price discovery")
    w("")
    w(f"*Auto-generated by `scripts/leadlag_note.py` on "
      f"{datetime.now(UTC):%Y-%m-%d %H:%M} UTC from `data/history/` "
      f"(same recorded snapshots as the edge-persistence note).*")
    w("")
    w("## Method")
    w("")
    w(f"Mids move sparsely at snapshot cadence, so raw return "
      f"cross-correlation is dominated by zeros. Instead, move-conditional "
      f"analysis: a *move* is a mid change of at least "
      f"{THRESHOLD * 100}¢ between consecutive co-observed snapshots; for "
      f"every venue-A move we look ahead up to {HORIZON} snapshots for "
      f"venue B's first move and classify it follow (same direction), "
      f"oppose, or unanswered. Same-tick moves land in a `simultaneous` "
      f"bucket — sub-cadence leadership is unobservable and never "
      f"attributed. Recording gaps split sessions; nothing is measured "
      f"across a gap. The test statistic is an exact two-sided binomial on "
      f"follows vs opposes against p = 0.5.")
    w("")
    w("## Per-pair results (0.25¢ threshold)")
    w("")
    w("Columns: moves | simultaneous | follow/oppose/unanswered | follow "
      "rate (of directional answers) | median follow lag | binomial p")
    w("")
    w("| pair | leader | moves | simul | F/O/U | follow | med lag | p |")
    w("|---|---|---:|---:|---:|---:|---:|---:|")
    for key, (k, p) in per_pair.items():
        w(f"| {key} | kalshi→pm | {fmt(k)} |")
        w("| | pm→kalshi | " + fmt(p) + " |")
    w("")
    w("## Pooled across all pairs")
    w("")
    w("| leader | moves | simul | F/O/U | follow | med lag | p |")
    w("|---|---:|---:|---:|---:|---:|---:|")
    w(f"| kalshi→pm | {fmt(pooled_k)} |")
    w(f"| pm→kalshi | {fmt(pooled_p)} |")
    w("")

    # interpretation, computed
    def rate(r: LeadLag) -> float | None:
        n = r.follows + r.opposes
        return r.follows / n if n else None

    rk, rp = rate(pooled_k), rate(pooled_p)
    w("## Reading")
    w("")
    if rk is not None and rp is not None:
        leader = "Kalshi" if (rk - (rp or 0)) > 0.05 else (
            "Polymarket" if ((rp or 0) - rk) > 0.05 else None)
        if leader:
            w(f"- Directional answers favor **{leader} leading**: its moves "
              f"are followed at {max(rk, rp):.0%} vs {min(rk, rp):.0%} the "
              f"other way. Check the p-values above before leaning on this "
              f"— the sample grows daily.")
        else:
            w(f"- No clear leader at this cadence: follow rates "
              f"{rk:.0%} (K→PM) vs {rp:.0%} (PM→K). Much of the action is "
              f"in the `simultaneous` bucket — leadership, if any, plays "
              f"out faster than the snapshot cadence.")
    w(f"- {pooled_k.simultaneous + pooled_p.simultaneous} same-tick move "
      f"pairs vs {pooled_k.follows + pooled_p.follows} cross-tick follows: "
      f"the cadence floor is doing real censoring; the BYOK websocket feed "
      f"(sub-second) will sharpen this materially.")
    w("- Unanswered moves are informative too: a venue whose moves the "
      "other never validates is either discovering price alone or drifting "
      "on noise/one-sided flow.")
    w("")
    w("## Threshold sensitivity (pooled)")
    w("")
    w("| threshold | kalshi→pm follow (p) | pm→kalshi follow (p) |")
    w("|---:|---:|---:|")
    for thr in [THRESHOLD] + SENSITIVITY:
        pk, pp = LeadLag(), LeadLag()
        for key in pairs:
            s = build_series(rows, key)
            if len(s.ts) < 50:
                continue
            pk.absorb(lead_follow(s, "kalshi", thr, HORIZON))
            pp.absorb(lead_follow(s, "polymarket", thr, HORIZON))
        def cell(r: LeadLag) -> str:
            n = r.follows + r.opposes
            if not n:
                return "—"
            pv = f"{r.p_value:.3f}" if r.p_value is not None else "—"
            return f"{r.follows / n:.0%} (p={pv}, n={n})"
        w(f"| {thr * 100}¢ | {cell(pk)} | {cell(pp)} |")
    w("")
    w("## Caveats")
    w("")
    w("- Both venues are sampled at the same instant per snapshot, so "
      "there is no cross-venue clock skew inside a tick — but anything "
      "faster than the cadence is invisible (see `simultaneous`).")
    w("- Kalshi mids move on a cent grid; Polymarket's finer grid produces "
      "more small moves — the threshold sensitivity table bounds how much "
      "that asymmetry matters.")
    w("- Events are pooled across pairs and days and treated as "
      "independent; clustered news moves violate that mildly.")
    w("- Sparse-sample study: rates are honest but confidence grows with "
      "the recorder (running continuously since 2026-07-21).")
    w("")
    w("*Upcoming: the 2026-07-29 Fed decision resolves the densest pair "
      "mid-recording — an event-study section lands here after it.*")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
