"""Generate docs/research/edge-persistence.md from recorded parquet history.

    python scripts/research_note.py

Re-run any time; the note is fully derived from data/history/ plus the
curated tables below (verified-at-recording flags from event_map.yaml git
history; approximate resolution timestamps). Every number is computed with
Decimal from the decimal128 columns — the note can understate, never
overstate.
"""

import statistics
from collections import defaultdict
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path

import pyarrow.parquet as pq

from tinli_backtest import ASSUMPTIONS, backtest, extract_episodes

REPO = Path(__file__).resolve().parents[1]
HISTORY = REPO / "data" / "history"
OUT = REPO / "docs" / "research" / "edge-persistence.md"

# criteria_verified AS OF the recording date, from data/event_map.yaml git
# history (commits 06933c5 2026-07-06, 46d40d1 2026-07-16, 5467aa7
# 2026-07-20). A pair is tradeable in the backtest only while verified.
VERIFIED = {
    # 2026-07-06 map (recorded 2026-07-13..15): all verified except the trap
    "wc26-advance-usa-belgium": True, "wc26-advance-portugal-spain": True,
    "wc26-advance-argentina-egypt": True, "wc26-advance-france-morocco": True,
    "wc26-advance-switzerland-colombia": True, "wc26-champion-norway": True,
    "wc26-champion-usa": True, "wc26-champion-france": True,
    "wc26-champion-england": True, "wc26-champion-argentina": True,
    "wim26-mens-djokovic": True, "wim26-mens-sinner": True,
    "wim26-mens-fritz": True, "wim26-mens-auger-aliassime": True,
    "wim26-womens-osaka": True, "wim26-r16-deminaur-cobolli": True,
    "wim26-r16-fritz-bublik": True, "wim26-r16-dimitrov-fery": True,
    "fed-jul26-cut-25bps": True, "fed-jul26-no-change": True,
    "wc26-best-host-usa": False,  # the deliberate trap example
    # 2026-07-16 map (recorded 2026-07-17)
    "wc26-winner-argentina": True, "wc26-winner-spain": True,
    "wc26-final-arg-wins-3-2": True,
    "wc26-third-place-france": False, "wc26-golden-boot-messi": False,
    # 2026-07-20 map (recorded 2026-07-21..)
    "bdor26-yamal": True, "bdor26-kane": True, "bdor26-rodri": True,
    "lebron-next-gsw": False, "lebron-next-nyk": False, "lebron-next-sas": False,
}

# Approximate resolution timestamps (UTC) for pairs that produced trades —
# used ONLY for capital-duration / annualization, clearly labeled approx.
RESOLUTIONS = {
    "wc26-champion-france": datetime(2026, 7, 19, 22, 0, tzinfo=UTC),
    "wc26-champion-england": datetime(2026, 7, 19, 22, 0, tzinfo=UTC),
    "wc26-champion-argentina": datetime(2026, 7, 19, 22, 0, tzinfo=UTC),
    "fed-jul26-no-change": datetime(2026, 7, 29, 18, 0, tzinfo=UTC),
    "fed-jul26-cut-25bps": datetime(2026, 7, 29, 18, 0, tzinfo=UTC),
    "bdor26-yamal": datetime(2026, 10, 15, 0, 0, tzinfo=UTC),
    "bdor26-kane": datetime(2026, 10, 15, 0, 0, tzinfo=UTC),
    "bdor26-rodri": datetime(2026, 10, 15, 0, 0, tzinfo=UTC),
}

LATENCIES = [0, 1, 2, 3, 5, 10]


def load_rows() -> list[dict]:
    rows: list[dict] = []
    for f in sorted(HISTORY.rglob("*.parquet")):
        rows.extend(pq.read_table(f).to_pylist())
    return rows


def cents(x: Decimal | None) -> str:
    return "—" if x is None else f"{x * 100:.2f}¢"


def pctl(values, q):
    if not values:
        return None
    s = sorted(values)
    return s[min(len(s) - 1, int(q * len(s)))]


def main() -> None:
    rows = load_rows()
    ts_all = sorted({r["ts"] for r in rows})
    gaps = [
        (b - a).total_seconds()
        for a, b in zip(ts_all, ts_all[1:])
        if (b - a).total_seconds() < 300
    ]
    cadence = statistics.median(gaps)
    pairs = sorted({r["event_key"] for r in rows})

    by_pair = defaultdict(list)
    for r in rows:
        by_pair[r["event_key"]].append(r)

    lines: list[str] = []
    w = lines.append
    w("# Edge persistence and a lock backtest on recorded venue data")
    w("")
    w(f"*Auto-generated by `scripts/research_note.py` on "
      f"{datetime.now(UTC):%Y-%m-%d %H:%M} UTC. Every number derives from "
      f"`data/history/` decimal128 parquet; edges were floor-quantized at "
      f"recording time, so this note can understate but not overstate.*")
    w("")
    # computed after the analysis below; placeholder index to fill in
    findings_at = len(lines)
    w("")  # replaced by the Findings section at the end

    w("## Question")
    w("")
    w("Cross-venue prediction-market arbitrage looks easy on a screen: the "
      "same event trades on Kalshi and Polymarket, and their prices "
      "disagree. After exact taker fees, at the size the books actually "
      "display, do executable lock edges exist — how large, how long-lived, "
      "and what could a taker at human/retail latency have captured?")
    w("")
    w("## Data")
    w("")
    w(f"- {len(rows):,} pair-ticks across {len(pairs)} curated pairs, "
      f"{len(ts_all):,} distinct snapshots, {ts_all[0]:%Y-%m-%d} to "
      f"{ts_all[-1]:%Y-%m-%d} (recording ongoing).")
    w(f"- Median snapshot cadence {cadence:.0f}s — episode lifetimes below "
      f"this are unobservable; single-tick episodes mean lifetime < cadence.")
    w("- Each tick stores executable top-of-book on both venues, the "
      "fee-adjusted per-contract lock edge, the edge at executable size, "
      "and that size (see `tinli_divergence`).")
    w("")

    # -- edge existence ------------------------------------------------------
    w("## 1. Fee-adjusted at-size edges are rare")
    w("")
    w("| pair | verified | ticks | +edge ticks | share | med edge | max edge | max size |")
    w("|---|---|---:|---:|---:|---:|---:|---:|")
    total_pos = 0
    for key in pairs:
        prs = by_pair[key]
        pos = [r for r in prs
               if r["edge_at_size"] is not None and r["edge_at_size"] > 0
               and r["max_lock_size"] is not None and r["max_lock_size"] > 0]
        total_pos += len(pos)
        if not pos:
            continue
        edges = [r["edge_at_size"] for r in pos]
        sizes = [r["max_lock_size"] for r in pos]
        w(f"| {key} | {'yes' if VERIFIED.get(key) else '**NO — trap**'} "
          f"| {len(prs):,} | {len(pos)} | {len(pos) / len(prs):.1%} "
          f"| {cents(pctl(edges, 0.5))} | {cents(max(edges))} "
          f"| {max(sizes):,.0f} |")
    share = total_pos / len(rows)
    w("")
    w(f"Across ALL {len(rows):,} pair-ticks, {total_pos} ({share:.2%}) "
      f"showed a positive fee-adjusted edge at displayed size. Fees erase "
      f"almost every raw-basis dislocation; pairs not listed above never "
      f"showed one.")
    w("")

    # -- episodes ------------------------------------------------------------
    verified_keys = [k for k in pairs if VERIFIED.get(k)]
    eps_by_pair = {k: extract_episodes(by_pair[k], k) for k in verified_keys}
    all_eps = [e for eps in eps_by_pair.values() for e in eps]
    w("## 2. When edges appear, they persist (at this cadence)")
    w("")
    w("| pair | episodes | med lifetime | p90 | max |")
    w("|---|---:|---:|---:|---:|")
    for key in verified_keys:
        eps = eps_by_pair[key]
        if not eps:
            continue
        durs = [e.duration_s for e in eps]
        w(f"| {key} | {len(eps)} | {pctl(durs, 0.5):.0f}s "
          f"| {pctl(durs, 0.9):.0f}s | {max(durs) / 60:.0f}m |")
    single = sum(1 for e in all_eps if len(e.ticks) == 1)
    w("")
    w(f"{len(all_eps)} episodes on verified pairs; {single} were single-tick "
      f"(true lifetime below the {cadence:.0f}s cadence). The long episodes "
      f"are the interesting finding: these books stayed crossed after fees "
      f"for minutes-to-hours, consistent with thin prediction-market "
      f"liquidity and no cross-venue market-making bridging them.")
    w("")

    # -- backtest ------------------------------------------------------------
    w("## 3. Lock backtest — one taker, product signal taken literally")
    w("")
    trades0 = backtest(all_eps, RESOLUTIONS, latency_ticks=0)
    w("| pair | locks | locked P&L | capital | return | ~annualized |")
    w("|---|---:|---:|---:|---:|---:|")
    per_pair = defaultdict(list)
    for t in trades0:
        per_pair[t.event_key].append(t)
    for key, ts in sorted(per_pair.items()):
        p = sum(t.profit for t in ts)
        c = sum(t.capital for t in ts)
        anns = [t.annualized_return for t in ts if t.annualized_return is not None]
        ann = f"{statistics.median(anns):.1%}" if anns else "—"
        w(f"| {key} | {len(ts)} | ${p} | ${c:,} | {p / c:.2%} | {ann} |")
    P = sum(t.profit for t in trades0)
    C = sum(t.capital for t in trades0)
    w(f"| **total** | **{len(trades0)}** | **${P}** | **${C:,}** "
      f"| **{P / C:.2%}** | |")
    w("")
    w("Locked profit is known at entry — a lock pays $1/contract at "
      "resolution regardless of outcome — so these are not "
      "mark-to-market P&Ls, they are settlement-guaranteed subject only to "
      "the execution assumptions below. Capital is the all-in cost "
      "(size × (1 − edge)). Annualized medians use approximate resolution "
      "dates and the same 6-hour floor as the product's lock report.")
    w("")

    # -- latency decay -------------------------------------------------------
    w("## 4. Latency decay — the edge does not wait for you")
    w("")
    w(f"Entering k snapshots (~{cadence:.0f}s each) after an episode first "
      f"appears:")
    w("")
    w("| latency (ticks) | ≈ delay | locks still available | locked P&L | vs instant |")
    w("|---:|---:|---:|---:|---:|")
    for k in LATENCIES:
        tk = backtest(all_eps, RESOLUTIONS, latency_ticks=k)
        pk = sum(t.profit for t in tk)
        w(f"| {k} | {k * cadence:.0f}s | {len(tk)} | ${pk} "
          f"| {pk / P:.0%} |")
    w("")

    # -- traps ---------------------------------------------------------------
    trap_pos = defaultdict(list)
    for key in pairs:
        if VERIFIED.get(key):
            continue
        for r in by_pair[key]:
            if r["edge_at_size"] is not None and r["edge_at_size"] > 0:
                trap_pos[key].append(r["edge_at_size"])
    w("## 5. Flagged pairs showed 'edges' too — that is why they are flagged")
    w("")
    if trap_pos:
        for key, edges in sorted(trap_pos.items()):
            w(f"- `{key}`: {len(edges)} apparent +edge ticks (max "
              f"{cents(max(edges))}) — **excluded**. Resolution criteria "
              f"were not verified equivalent; a 'lock' can settle both legs "
              f"against you (e.g. the LeBron pairs' 8-day settlement-window "
              f"gap documented in `data/event_map.yaml`).")
    else:
        w("- none in this window.")
    w("")

    # -- assumptions / caveats ----------------------------------------------
    w("## Assumptions and caveats")
    w("")
    for a in ASSUMPTIONS:
        w(f"- {a}")
    w("- Snapshot cadence bounds observability: sub-cadence edges are "
      "invisible, and true episode lifetimes are only bracketed.")
    w("- Resolution timestamps for annualization are approximate "
      "(settlement can lag close).")
    w("- One recording machine, one network vantage point; venue APIs were "
      "polled/streamed as documented in `docs/VENUES.md`.")
    w("")
    w("*Recorder: Windows scheduled task running `scripts/snapshot.py "
      "--loop 60` since 2026-07-21 (earlier windows at similar cadence). "
      "Re-run this script as data accumulates.*")

    # -- findings TL;DR (needs the computed numbers, hence written last) -----
    k5 = backtest(all_eps, RESOLUTIONS, latency_ticks=5)
    p5 = sum(t.profit for t in k5)
    durs_all = [e.duration_s for e in all_eps]
    findings = [
        "## Findings",
        "",
        f"1. **Executable edges are rare but real.** {share:.2%} of "
        f"{len(rows):,} recorded pair-ticks showed a positive lock edge "
        f"after exact taker fees at displayed size (max "
        f"{cents(max(r['edge_at_size'] for r in rows if r['edge_at_size'] is not None))} "
        f"per contract).",
        f"2. **They persist far longer than an efficient market would "
        f"allow.** {len(all_eps)} episodes on verified pairs, median "
        f"lifetime {pctl(durs_all, 0.5):.0f}s, longest "
        f"{max(durs_all) / 60:.0f} minutes of continuously executable "
        f"after-fee edge. No one is bridging these venues at size.",
        f"3. **The binding constraint is capacity, not latency.** A taker "
        f"entering ~{5 * cadence:.0f}s late still captures "
        f"{p5 / P:.0%} of instant-entry P&L — but taking every edge in "
        f"{(ts_all[-1] - ts_all[0]).days} days locks only ${P} on "
        f"${C:,.0f} deployed ({P / C:.2%} absolute). Displayed depth, not "
        f"reaction time, is what caps this trade at retail scale.",
        "",
    ]
    lines[findings_at:findings_at + 1] = findings

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
